import { useState } from "react";
import { motion } from "motion/react";
import {
  ArrowLeft, ArrowRight, Check, ChevronRight, CircleHelp, Copy, Crown,
  LoaderCircle, Lock, LockKeyhole, MessageCircle, Mic, MicOff, RotateCcw,
  Send, Settings2, ShieldCheck, Sparkles, Timer, Users, Volume2, VolumeX, Vote
} from "lucide-react";

type Avatar = { name: string; color: string; face: string; accessory: string; outfit: string; personality: string; points: number; host?: boolean };

const flow = ["Splash", "Welcome", "Join Room", "Host Settings", "Lobby", "Writer Input", "Waiting", "Role Reveal", "Ready", "Clue Turn", "Discussion", "Result", "Scoreboard", "Next Round"];
const clueOptions = ["∞ Unlimited", "15s", "30s", "45s", "1m", "2m", "3m", "4m", "5m"];
const discussionOptions = ["∞ Unlimited", "30s", "1m", "2m", "3m", "5m", "7m", "10m"];
const avatarCatalog: Avatar[] = [
  { name: "Mochi", color: "bg-[#f5a6bd]", face: "•ᴗ•", accessory: "🎀", outfit: "rose cardigan", personality: "sunny", points: 80, host: true },
  { name: "Lumi", color: "bg-[#a8d9f4]", face: "˶ᵔ ᵕ ᵔ˶", accessory: "⭐", outfit: "sky hoodie", personality: "dreamy", points: 70 },
  { name: "Pip", color: "bg-[#b7e6c9]", face: "ᵔᴥᵔ", accessory: "🌼", outfit: "mint vest", personality: "bubbly", points: 55 },
  { name: "Taro", color: "bg-[#cdbcf1]", face: "•̀ᴗ•́", accessory: "🧢", outfit: "violet tee", personality: "mischievous", points: 40 },
  { name: "Nori", color: "bg-[#ffd3a7]", face: "ᵕ̈", accessory: "🪼", outfit: "apricot scarf", personality: "curious", points: 35 },
  { name: "Boba", color: "bg-[#b8d6c1]", face: "ᵔⰙᵔ", accessory: "🍃", outfit: "forest overalls", personality: "gentle", points: 30 },
  { name: "Coco", color: "bg-[#d7b5a1]", face: "•⩊•", accessory: "🧣", outfit: "cocoa knit", personality: "cozy", points: 25 },
  { name: "Mimi", color: "bg-[#f4c9e7]", face: "◕ᴗ◕", accessory: "🦋", outfit: "petal dress", personality: "sweet", points: 20 },
  { name: "Tutu", color: "bg-[#9fd4d8]", face: "⌒ᴗ⌒", accessory: "🐚", outfit: "aqua romper", personality: "calm", points: 18 },
  { name: "Poppy", color: "bg-[#f3aa89]", face: "•ω•", accessory: "🍓", outfit: "coral pinafore", personality: "bold", points: 14 },
  { name: "Wink", color: "bg-[#d4c7a6]", face: "-ᴗ•", accessory: "🕶️", outfit: "sand jacket", personality: "sly", points: 10 },
  { name: "Mallow", color: "bg-[#e8e0f6]", face: "˙ᵕ˙", accessory: "☁️", outfit: "lilac cape", personality: "floaty", points: 8 },
  { name: "Peachy", color: "bg-[#ffc8bd]", face: "ᵔᵕᵔ", accessory: "🍑", outfit: "peach bow", personality: "cheery", points: 0 },
  { name: "Minty", color: "bg-[#bcebd7]", face: "•‿•", accessory: "🪴", outfit: "leaf collar", personality: "thoughtful", points: 0 },
  { name: "Dottie", color: "bg-[#f9e58d]", face: "•ᴗ<", accessory: "🎨", outfit: "sunny smock", personality: "artsy", points: 0 },
  { name: "Berry", color: "bg-[#ce9cbd]", face: "ᵔ⩊ᵔ", accessory: "🫐", outfit: "plum cape", personality: "brave", points: 0 },
  { name: "Kiki", color: "bg-[#a6c5ee]", face: "⌯'▾'⌯", accessory: "🎧", outfit: "denim hoodie", personality: "musical", points: 0 },
  { name: "Dumpling", color: "bg-[#f3dcc7]", face: "˶•⩊•˶", accessory: "🥟", outfit: "cream jumper", personality: "shy", points: 0 },
  { name: "Puddle", color: "bg-[#91c6e2]", face: "´꒳`", accessory: "☔", outfit: "rain poncho", personality: "chill", points: 0 },
  { name: "Fizzy", color: "bg-[#f4a8b1]", face: "^ᴗ^", accessory: "🫧", outfit: "bubble vest", personality: "sparkly", points: 0 },
  { name: "Sprout", color: "bg-[#c8d986]", face: "ᵔᴗᵔ", accessory: "🌱", outfit: "sage dungarees", personality: "helpful", points: 0 },
  { name: "Tinsel", color: "bg-[#d8c1f0]", face: "•ᵕ•", accessory: "✨", outfit: "star poncho", personality: "glam", points: 0 },
  { name: "Crumb", color: "bg-[#e6c28f]", face: "ᵔₒᵔ", accessory: "🥨", outfit: "biscuit vest", personality: "goofy", points: 0 },
  { name: "Sundae", color: "bg-[#f8d5d8]", face: "˘ᴗ˘", accessory: "🍒", outfit: "cherry tee", personality: "soft", points: 0 },
  { name: "Orbit", color: "bg-[#9c9ce2]", face: "°ᴗ°", accessory: "🪐", outfit: "space cape", personality: "clever", points: 0 },
  { name: "Panko", color: "bg-[#e5cfac]", face: "ᵕⰙᵕ", accessory: "🧁", outfit: "vanilla bib", personality: "warm", points: 0 },
  { name: "Zuzu", color: "bg-[#e6a9dc]", face: "•⌄•", accessory: "💜", outfit: "berry sweater", personality: "sassy", points: 0 },
  { name: "Miso", color: "bg-[#b6a18d]", face: "ᵔᵕᵔ", accessory: "🐾", outfit: "teddy hoodie", personality: "loyal", points: 0 },
  { name: "Taffy", color: "bg-[#e9b3cc]", face: "•ᴥ•", accessory: "🧸", outfit: "candy jacket", personality: "playful", points: 0 },
  { name: "Plum", color: "bg-[#a984ba]", face: "˶•ᵕ•˶", accessory: "🔮", outfit: "moon cloak", personality: "mysterious", points: 0 },
];

function Bean({ player, size = "md", ring = false }: { player: Avatar; size?: "xs" | "sm" | "md" | "lg"; ring?: boolean }) {
  const sizes = { xs: "size-8 text-[7px]", sm: "size-10 text-[9px]", md: "size-14 text-xs", lg: "size-24 text-lg" };
  return <motion.div initial={{ opacity: 0, scale: 0.72, y: 8 }} animate={{ opacity: 1, scale: 1, y: 0 }} whileHover={{ y: -3, rotate: 2 }} transition={{ type: "spring", stiffness: 360, damping: 18 }} title={`${player.name} · ${player.personality}`} className={`${sizes[size]} ${player.color} ${ring ? "ring-4 ring-white" : ""} relative grid shrink-0 place-items-center rounded-[45%_45%_48%_48%] border-2 border-white/80 font-bold text-[#604d66] shadow-[0_5px_0_rgba(125,92,121,.12)]`}><span className="absolute -top-2 right-0 text-[12px] leading-none">{player.accessory}</span><span className="translate-y-1 whitespace-nowrap">{player.face}</span><span className="absolute -bottom-1 size-2 rounded-full bg-white/70" /></motion.div>;
}
function Badge({ children, tone = "pink" }: { children: React.ReactNode; tone?: "pink" | "mint" | "lavender" | "cream" }) {
  const colors = { pink: "bg-[#ffe1eb] text-[#b04f73]", mint: "bg-[#dcf3e8] text-[#4b8f72]", lavender: "bg-[#ece6ff] text-[#6e61a7]", cream: "bg-[#fff2cd] text-[#9a7734]" };
  return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-extrabold tracking-wide ${colors[tone]}`}>{children}</span>;
}
function Button({ children, onClick, variant = "primary", disabled = false, icon: Icon, className = "" }: { children: React.ReactNode; onClick?: () => void; variant?: "primary" | "soft" | "ghost"; disabled?: boolean; icon?: React.ElementType; className?: string }) {
  const variants = { primary: "bg-[#ef6d9a] text-white shadow-[0_5px_0_#cf547e] hover:translate-y-0.5 hover:shadow-[0_3px_0_#cf547e]", soft: "bg-[#edf8f2] text-[#43866b] shadow-[0_4px_0_#c6e8d6]", ghost: "bg-white/80 text-[#74647d] shadow-[0_3px_0_#eadce5]" };
  return <motion.button whileHover={disabled ? {} : { y: -1 }} whileTap={disabled ? {} : { scale: 0.97, y: 2 }} transition={{ type: "spring", stiffness: 500, damping: 24 }} disabled={disabled} onClick={onClick} className={`flex h-13 w-full items-center justify-center gap-2 rounded-2xl px-5 font-extrabold transition-all disabled:cursor-not-allowed disabled:opacity-45 ${variants[variant]} ${className}`}>{Icon && <Icon size={18} strokeWidth={2.5}/>} {children}</motion.button>;
}
function Top({ title, sub, back, onBack }: { title: string; sub?: string; back?: boolean; onBack?: () => void }) { return <div className="mb-5 flex items-start gap-3"><button aria-label="Back" onClick={onBack} className={`mt-1 grid size-9 place-items-center rounded-xl bg-white text-[#7d6a81] shadow-sm ${back ? "" : "invisible"}`}><ArrowLeft size={18}/></button><div className="min-w-0 flex-1"><p className="font-mono text-[10px] font-medium uppercase tracking-[.16em] text-[#a58da2]">Mallow Mystery</p><h1 className="font-[Baloo_2] text-[30px] font-extrabold leading-8 tracking-[-.02em] text-[#493e58]">{title}</h1>{sub && <p className="mt-1 text-[13px] font-bold leading-5 text-[#887a8d]">{sub}</p>}</div></div>; }
function VoiceControls({ micOn, setMicOn, speakerOn, setSpeakerOn }: any) { return <div className="flex gap-1.5"><button aria-label="Toggle microphone" onClick={() => setMicOn(!micOn)} className={`grid size-8 place-items-center rounded-xl transition ${micOn ? "bg-[#e2f4ea] text-[#4d9575]" : "bg-[#ffe5e7] text-[#d66470]"}`}>{micOn ? <Mic size={16}/> : <MicOff size={16}/>}</button><button aria-label="Toggle speaker" onClick={() => setSpeakerOn(!speakerOn)} className={`grid size-8 place-items-center rounded-xl transition ${speakerOn ? "bg-[#e9e3fb] text-[#7561aa]" : "bg-[#f2edf1] text-[#9a8b99]"}`}>{speakerOn ? <Volume2 size={16}/> : <VolumeX size={16}/>}</button></div>; }
function TimerRing({ value, label, tone = "pink" }: { value: string; label: string; tone?: "pink" | "blue" }) { const colors = tone === "pink" ? "border-[#ef8cad] bg-[#fff3f7] text-[#db668c]" : "border-[#8fc9e5] bg-[#effaff] text-[#5c96b5]"; return <motion.div animate={{ rotate: [0, 1.5, -1.5, 0] }} transition={{ duration: 3.2, repeat: Infinity, ease: "easeInOut" }} className={`grid size-28 place-items-center rounded-full border-[7px] ${colors} shadow-[0_4px_0_rgba(123,91,117,.12)]`}><div className="text-center"><p className="font-[Baloo_2] text-xl font-extrabold leading-5">{value}</p><p className="mt-1 text-[9px] font-extrabold uppercase tracking-widest">{label}</p></div></motion.div>; }
function SliderCard({ title, helper, value, setValue, options, locked }: any) { return <div className="rounded-[25px] bg-white p-4 shadow-[0_4px_0_#eee3e9]"><div className="mb-3 flex items-start justify-between gap-3"><div><h3 className="font-[Baloo_2] text-lg font-extrabold text-[#55495e]">{title}</h3><p className="text-xs font-bold text-[#a08d9d]">{helper}</p></div><Badge tone={locked ? "cream" : "lavender"}>{locked ? <><Lock size={10}/> LOCKED</> : options[value]}</Badge></div><input aria-label={title} disabled={locked} type="range" min="0" max={options.length - 1} value={value} onChange={e=>setValue(Number(e.target.value))} className="h-2 w-full cursor-pointer appearance-none rounded-full bg-[#f3e8ef] accent-[#ef7fa7] disabled:cursor-not-allowed"/><div className="mt-2 flex justify-between text-[9px] font-extrabold text-[#b19ba9]"><span>{options[0]}</span><span>{options[options.length - 1]}</span></div></div>; }

export default function MallowMystery() {
  const [screen, setScreen] = useState("Splash");
  const [nickname, setNickname] = useState("Lumi"); const [code, setCode] = useState("48291"); const [writerText, setWriterText] = useState("");
  const [rounds, setRounds] = useState(10); const [clueTime, setClueTime] = useState(2); const [discussionTime, setDiscussionTime] = useState(3);
  const [micOn, setMicOn] = useState(true); const [speakerOn, setSpeakerOn] = useState(true); const [ready, setReady] = useState(false);
  const [selectedVote, setSelectedVote] = useState("Mochi"); const [voteSubmitted, setVoteSubmitted] = useState(false);
  const [roster] = useState(() => avatarCatalog.slice(0, 12));
  const go = (s: string) => setScreen(s); const back = () => go(flow[Math.max(0, flow.indexOf(screen) - 1)] ?? "Splash");
  const gameStarted = flow.indexOf(screen) >= flow.indexOf("Writer Input"); const settingsLocked = gameStarted;
  const p = { go, back, nickname, setNickname, code, setCode, writerText, setWriterText, rounds, setRounds, clueTime, setClueTime, discussionTime, setDiscussionTime, settingsLocked, roster, ready, setReady, selectedVote, setSelectedVote, voteSubmitted, setVoteSubmitted };
  let content: React.ReactNode;
  switch (screen) { case "Splash": content = <Splash go={go}/>; break; case "Welcome": content = <Welcome go={go}/>; break; case "Join Room": content = <Join {...p}/>; break; case "Host Settings": content = <HostSettings {...p}/>; break; case "Lobby": content = <Lobby {...p}/>; break; case "Writer Input": content = <Writer {...p}/>; break; case "Waiting": content = <Waiting {...p}/>; break; case "Role Reveal": content = <Role {...p}/>; break; case "Ready": content = <Ready {...p}/>; break; case "Clue Turn": content = <Clue {...p}/>; break; case "Discussion": content = <Discussion {...p}/>; break; case "Result": content = <Result {...p}/>; break; case "Scoreboard": content = <Scoreboard {...p}/>; break; default: content = <NextRound {...p}/>; }
  return <main className="min-h-screen bg-[#f5eef4] p-3 font-[Nunito] text-foreground sm:p-8"><div className="mx-auto flex min-h-[780px] w-full max-w-[430px] flex-col overflow-hidden rounded-[36px] border-[7px] border-white bg-[#fffaf8] shadow-[0_22px_70px_rgba(116,78,115,.18)]"><div className="flex items-center justify-between px-7 py-4"><span className="font-mono text-[10px] font-bold tracking-widest text-[#887a8d]">9:41</span><div className="h-2 w-23 rounded-full bg-[#5b5265]"/>{gameStarted ? <VoiceControls micOn={micOn} setMicOn={setMicOn} speakerOn={speakerOn} setSpeakerOn={setSpeakerOn}/> : <span className="text-xs">●●●</span>}</div><motion.div key={screen} initial={{ opacity: 0, y: 18, scale: 0.985 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ type: "spring", stiffness: 260, damping: 24 }} className="flex flex-1 flex-col px-6 pb-6">{content}</motion.div><div className="flex gap-1.5 px-7 pb-5">{flow.map((item, i)=><button aria-label={item} key={item} onClick={()=>go(item)} className={`h-1.5 rounded-full transition-all ${item===screen?"w-8 bg-[#ef6d9a]":i<flow.indexOf(screen)?"w-3 bg-[#f5b6ca]":"w-3 bg-[#eadfe7]"}`}/>)}</div></div></main>;
}
function Splash({ go }: any) { return <div className="flex flex-1 flex-col items-center justify-between py-8 text-center"><div className="mt-10 relative"><div className="absolute -left-10 top-1 size-9 rounded-full bg-[#cfeaf7]"/><div className="absolute -right-10 top-12 size-6 rounded-full bg-[#ffe0a4]"/><div className="grid size-40 place-items-center rounded-[45%] border-4 border-white bg-[#f6b2c8] text-4xl shadow-[inset_0_-12px_0_rgba(218,111,148,.25),0_12px_0_#e990ae]">⌣</div><Sparkles className="absolute -right-3 -top-3 text-[#c3adeb]"/></div><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.25em] text-[#ad90a5]">a tiny game of trust</p><h1 className="mt-1 font-[Baloo_2] text-5xl font-extrabold leading-[.85] text-[#51455e]">mallow<br/><span className="text-[#ef6d9a]">mystery</span></h1><p className="mx-auto mt-5 max-w-60 text-sm font-bold leading-6 text-[#8b7d91]">Find the fibber before the clues run out.</p></div><Button onClick={()=>go("Welcome")} icon={ArrowRight}>Tap to play</Button></div>; }
function Welcome({ go }: any) { return <div className="flex flex-1 flex-col"><Top title="Gather your beans" sub="A cozy little mystery for 3–30 friends."/><div className="relative my-auto flex justify-center py-8"><div className="absolute size-52 rounded-full bg-[#fbe9ef]"/>{avatarCatalog.slice(0,3).map((p,i)=><div key={p.name} className={`${i ? "-ml-5 mt-6" : ""} relative`}><Bean player={p} size="lg" ring/></div>)}</div><div className="space-y-3"><Button onClick={()=>go("Join Room")} icon={Users}>Join a room</Button><Button variant="soft" onClick={()=>go("Host Settings")} icon={Settings2}>Make a new room</Button></div></div>; }
function Join({ go, back, nickname, setNickname, code, setCode }: any) { return <div className="flex flex-1 flex-col"><Top title="Find your friends" sub="Pop in the room code your host shared." back onBack={back}/><div className="space-y-5"><label className="block text-xs font-extrabold uppercase tracking-[.13em] text-[#8c788b]">Room code<input value={code} maxLength={5} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} className="mt-2 h-16 w-full rounded-2xl border-2 border-[#e8d8e3] bg-[#fff9fc] px-4 text-center font-mono text-2xl font-bold tracking-[.32em] text-[#64526b] outline-none focus:border-[#ef8dad]"/></label><label className="block text-xs font-extrabold uppercase tracking-[.13em] text-[#8c788b]">Your nickname<input value={nickname} maxLength={12} onChange={e=>setNickname(e.target.value)} className="mt-2 h-14 w-full rounded-2xl border-2 border-[#e8d8e3] bg-[#fff9fc] px-4 text-base font-bold text-[#594c63] outline-none focus:border-[#ef8dad]"/></label><div className="rounded-2xl bg-[#fff0cf] p-3 text-xs font-bold leading-5 text-[#8f7134]"><CircleHelp className="mr-1 inline size-4"/>Your name is visible to everyone in the room.</div></div><div className="mt-auto"><Button disabled={code.length!==5||!nickname.trim()} onClick={()=>go("Host Settings")} icon={ArrowRight}>Continue</Button></div></div>; }
function HostSettings({ go, back, rounds, setRounds, clueTime, setClueTime, discussionTime, setDiscussionTime, settingsLocked }: any) { return <div className="flex flex-1 flex-col"><Top title="Host’s cozy controls" sub="Choose the pace before the mystery begins." back onBack={back}/><div className="flex-1 space-y-3 overflow-y-auto pb-3 [scrollbar-width:none]"><SliderCard title="Number of rounds" helper="How many tiny mysteries?" value={rounds - 1} setValue={(v:number)=>setRounds(v + 1)} options={Array.from({length:50},(_,i)=>String(i+1))} locked={settingsLocked}/><SliderCard title="Clue time" helper="For each player’s clue" value={clueTime} setValue={setClueTime} options={clueOptions} locked={settingsLocked}/><SliderCard title="Discussion time" helper="For the whole bean debate" value={discussionTime} setValue={setDiscussionTime} options={discussionOptions} locked={settingsLocked}/><div className="rounded-2xl bg-[#f4efff] p-3 text-xs font-bold leading-5 text-[#75658f]"><Lock className="mr-1 inline size-4"/>Settings lock automatically as soon as the game begins.</div></div><Button onClick={()=>go("Lobby")} icon={Check}>Save & enter lobby</Button></div>; }
function Lobby({ go, back, code, roster, rounds, clueTime, discussionTime }: any) { return <div className="flex flex-1 flex-col"><Top title="The Cozy Corner" sub="Waiting for the whole little bunch." back onBack={back}/><div className="mb-3 flex items-center justify-between rounded-2xl bg-[#eee8ff] px-4 py-3"><div><p className="text-[10px] font-extrabold uppercase tracking-widest text-[#766da1]">Room code</p><p className="font-mono text-lg font-bold tracking-widest text-[#564d79]">{code}</p></div><button aria-label="Copy room code" className="grid size-10 place-items-center rounded-xl bg-white text-[#756a99]"><Copy size={17}/></button></div><div className="mb-3 flex items-center justify-between"><Badge tone="mint"><Users size={11}/> {roster.length}/30 BEANS</Badge><span className="text-xs font-bold text-[#a18c9e]">3 needed to start</span></div><div className="flex-1 space-y-2 overflow-y-auto [scrollbar-width:none]">{roster.map((p:Avatar,i:number)=><div key={p.name} className="flex items-center gap-3 rounded-2xl bg-white p-2.5 shadow-[0_3px_0_#f0e5eb]"><Bean player={p} size="sm"/><div className="min-w-0 flex-1"><p className="font-extrabold text-[#584b61]">{p.name}</p><p className="text-[10px] font-bold text-[#a08b9d]">{p.outfit} · {p.personality}</p></div>{i===0?<Badge tone="cream"><Crown size={11}/> HOST</Badge>:<Badge tone="mint"><Check size={11}/> READY</Badge>}</div>)}</div><div className="mt-3 flex gap-2 rounded-2xl bg-[#fff4f8] p-3 text-center text-[10px] font-extrabold text-[#956b81]"><span>✦ {rounds} rounds</span><span>·</span><span>⌛ {clueOptions[clueTime]}</span><span>·</span><span>💬 {discussionOptions[discussionTime]}</span></div><div className="mt-3"><Button onClick={()=>go("Writer Input")} icon={Sparkles}>Start game</Button></div></div>; }
function Writer({ go, back, writerText, setWriterText }: any) { return <div className="flex flex-1 flex-col"><Top title="You’re the Writer!" sub="Give the other beans a real secret clue." back onBack={back}/><div className="my-auto rounded-[28px] bg-[#fce7ee] p-5 shadow-[0_5px_0_#f7d5e0]"><Badge tone="pink"><LockKeyhole size={11}/> ONLY YOU SEE THIS</Badge><h2 className="mt-4 font-[Baloo_2] text-2xl font-extrabold text-[#5b475b]">The secret word is<br/><span className="text-[#e26391]">“strawberry”</span></h2><textarea value={writerText} onChange={e=>setWriterText(e.target.value)} placeholder="Write a clever clue…" className="mt-5 h-28 w-full resize-none rounded-2xl border-2 border-white bg-white/85 p-4 text-sm font-bold text-[#68576c] outline-none placeholder:text-[#c3acb8] focus:border-[#ef8dad]"/></div><Button disabled={!writerText.trim()} onClick={()=>go("Waiting")} icon={Send}>Send clue</Button></div>; }
function Waiting({ go, back }: any) { return <div className="flex flex-1 flex-col"><Top title="Clue delivered!" sub="Let the suspense get cozy." back onBack={back}/><div className="my-auto text-center"><div className="mx-auto grid size-28 place-items-center rounded-full bg-[#e2f5eb] text-[#69a98c] shadow-[0_8px_0_#ccebd9]"><LoaderCircle className="size-10 animate-spin"/></div><h2 className="mt-7 font-[Baloo_2] text-2xl font-extrabold text-[#51445a]">Shuffling the roles…</h2></div><Button onClick={()=>go("Role Reveal")} icon={ChevronRight}>Reveal my role</Button></div>; }
function Role({ go, back }: any) { return <div className="flex flex-1 flex-col"><Top title="Your tiny secret" sub="Don’t let the others peek!" back onBack={back}/><div className="my-auto rounded-[30px] bg-[#ded7fb] p-6 text-center shadow-[0_8px_0_#c8bfe9]"><div className="mx-auto grid size-20 place-items-center rounded-3xl bg-white text-3xl shadow-sm">🕵️</div><Badge tone="lavender">YOUR ROLE</Badge><h2 className="mt-4 font-[Baloo_2] text-3xl font-extrabold text-[#5b517c]">Detective</h2><p className="mt-3 text-sm font-bold leading-6 text-[#6f668d]">Listen closely, then vote for the bean who doesn’t know the secret.</p></div><Button onClick={()=>go("Ready")} icon={ShieldCheck}>I’ve got it</Button></div>; }
function Ready({ go, back, ready, setReady, roster }: any) { return <div className="flex flex-1 flex-col"><Top title="Everybody ready?" sub="A quick nod before clues begin." back onBack={back}/><div className="my-auto grid grid-cols-2 gap-3">{roster.slice(0,4).map((p:Avatar,i:number)=><div key={p.name} className={`rounded-3xl p-4 text-center ${i===1&&ready?"bg-[#dcf3e8]":"bg-white"} shadow-[0_3px_0_#efe3ea]`}><Bean player={p} size="md"/><p className="mt-2 font-extrabold text-[#5f5267]">{p.name}</p><Badge tone={i===1&&!ready?"cream":"mint"}>{i===1&&!ready?"WAITING":<><Check size={11}/> READY</>}</Badge></div>)}</div><Button onClick={()=>ready?go("Clue Turn"):setReady(true)} icon={ready?ArrowRight:Check}>{ready?"Let’s begin":"I’m ready"}</Button></div>; }
function Clue({ go, back, roster, clueTime }: any) { const value = clueOptions[clueTime] ?? ""; return <div className="flex flex-1 flex-col"><Top title="Clue time" sub="Listen for the one word that doesn’t belong." back onBack={back}/><div className="my-auto text-center"><TimerRing value={value.startsWith("∞") ? "∞" : value} label={value.startsWith("∞") ? "Unlimited" : "left"}/><div className="relative mx-auto mt-7 w-fit"><Bean player={roster[0]} size="lg" ring/><span className="absolute -right-4 -top-2"><Badge tone="mint"><Mic size={11}/> SPEAKING</Badge></span></div><p className="mt-5 font-mono text-xs font-bold tracking-widest text-[#a08da1]">{roster[0].name.toUpperCase()}’S CLUE</p><div className="mt-3 rounded-[26px] bg-[#fff0d6] px-6 py-5 font-[Baloo_2] text-3xl font-extrabold text-[#79603e] shadow-[0_5px_0_#f2dfb8]">“juicy”</div></div><Button onClick={()=>go("Discussion")} icon={MessageCircle}>Open discussion</Button></div>; }
function Discussion({ go, back, roster, discussionTime, selectedVote, setSelectedVote, voteSubmitted, setVoteSubmitted }: any) { const value = discussionOptions[discussionTime] ?? ""; return <div className="flex flex-1 flex-col"><Top title="Talk it out" sub="Vote anytime — your choice locks once sent." back onBack={back}/><div className="flex items-center gap-4 rounded-[24px] bg-[#e8f4fc] p-3"><TimerRing value={value.startsWith("∞") ? "∞" : value} label={value.startsWith("∞") ? "Unlimited" : "left"} tone="blue"/><div className="min-w-0 flex-1"><Badge tone="mint"><Volume2 size={11}/> LIVE ROOM</Badge><p className="mt-2 text-xs font-bold leading-5 text-[#6c8da2]">Discussion ends when every bean votes, or time runs out.</p><div className="mt-2 flex -space-x-2">{roster.slice(0,5).map((p:Avatar)=><Bean key={p.name} player={p} size="xs" ring/>)}</div></div></div><div className="my-3 flex-1 space-y-2 overflow-y-auto [scrollbar-width:none]"><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#a58c9f]">Cast your one vote</p>{roster.slice(0,6).map((p:Avatar)=><button disabled={voteSubmitted} key={p.name} onClick={()=>setSelectedVote(p.name)} className={`flex w-full items-center gap-3 rounded-2xl border-2 p-2.5 text-left transition disabled:cursor-not-allowed ${selectedVote===p.name?"border-[#ed85a8] bg-[#fff1f6]":"border-transparent bg-white"}`}><Bean player={p} size="sm"/><span className="flex-1 font-extrabold text-[#5e5066]">{p.name}</span><span className={`grid size-6 place-items-center rounded-full border-2 ${selectedVote===p.name?"border-[#ed85a8] bg-[#ed85a8] text-white":"border-[#d9cbd5]"}`}>{selectedVote===p.name&&<Check size={14}/>}</span></button>)}</div>{voteSubmitted?<Button onClick={()=>go("Result")} icon={Sparkles}>Reveal result</Button>:<Button onClick={()=>setVoteSubmitted(true)} icon={Vote}>Submit vote</Button>}</div>; }
function Result({ go, back, roster }: any) { return <div className="flex flex-1 flex-col"><Top title="Mystery solved!" sub="The room has spoken." back onBack={back}/><div className="my-auto rounded-[30px] bg-[#fff0cf] p-6 text-center shadow-[0_7px_0_#f1ddb2]"><div className="mx-auto flex w-fit -space-x-4">{roster.slice(0,3).map((p:Avatar)=><Bean key={p.name} player={p} size="md" ring/>)}</div><p className="mt-6 font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#a47f35]">THE FIBBER WAS</p><h2 className="mt-1 font-[Baloo_2] text-4xl font-extrabold text-[#765835]">{roster[3].name}!</h2><p className="mt-3 text-sm font-bold leading-6 text-[#8d7049]">They didn’t know the word was <b>strawberry</b>. Nice catch!</p><Badge tone="cream">+20 DETECTIVE POINTS</Badge></div><Button onClick={()=>go("Scoreboard")} icon={ArrowRight}>View scores</Button></div>; }
function Scoreboard({ go, back, roster }: any) { return <div className="flex flex-1 flex-col"><Top title="After round one" sub="The bean board is getting spicy." back onBack={back}/><div className="flex-1 space-y-3">{[...roster].sort((a,b)=>b.points-a.points).slice(0,5).map((p,i)=><div key={p.name} className={`flex items-center gap-3 rounded-2xl p-3 ${i===0?"bg-[#f5edff]":"bg-white"} shadow-[0_3px_0_#eee3e9]`}><span className="w-5 text-center font-[Baloo_2] text-xl font-extrabold text-[#a990b6]">{i+1}</span><Bean player={p} size="sm"/><p className="flex-1 font-extrabold text-[#5e5065]">{p.name}</p><span className="font-mono text-sm font-bold text-[#817187]">{p.points}</span>{i===0&&<Crown size={17} className="text-[#d2a956]"/>}</div>)}</div><Button onClick={()=>go("Next Round")} icon={RotateCcw}>Start next round</Button></div>; }
function NextRound({ go, back }: any) { return <div className="flex flex-1 flex-col"><Top title="One more mystery?" sub="A new secret is waiting in the teapot." back onBack={back}/><div className="my-auto text-center"><div className="mx-auto grid size-28 place-items-center rounded-[40%] bg-[#cfe8f4] text-5xl shadow-[0_8px_0_#b2d7e7]">✦</div><h2 className="mt-7 font-[Baloo_2] text-3xl font-extrabold text-[#51445c]">Round two awaits.</h2><p className="mt-2 text-sm font-bold text-[#8d7d91]">Same room, fresh fibber, all new clues.</p></div><div className="space-y-3"><Button onClick={()=>go("Lobby")} icon={Users}>Back to lobby</Button><Button variant="ghost" onClick={()=>go("Writer Input")}>Keep this crew</Button></div></div>; }
